global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8081'  # usuario-api
          - 'host.docker.internal:8082'  # auth-api
          - 'host.docker.internal:8083'  # email-producer-api
          - 'host.docker.internal:8084'  # email-consumer-api
          - 'host.docker.internal:8080'  # gateway-api
