spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Marcklen/plataforma-fly-configs
          default-label: main
          search-paths: .
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          clone-on-start: true